<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PxaUkpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.pxaUkp_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pxaUkp_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lesson' => ['privates', '.errored..service_locator.pxaUkp_.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.pxaUkp_": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
        ]);
    }
}
