<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xd9ntTXService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Xd9ntTX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xd9ntTX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'course' => ['privates', '.errored..service_locator.Xd9ntTX.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.Xd9ntTX": it needs an instance of "App\\Entity\\Course" but this type has been excluded in "config/services.yaml".'],
            'courseRepository' => ['privates', 'App\\Repository\\CourseRepository', 'getCourseRepositoryService', true],
        ], [
            'course' => 'App\\Entity\\Course',
            'courseRepository' => 'App\\Repository\\CourseRepository',
        ]);
    }
}
