<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CourseController::delete' => ['privates', '.service_locator.Xd9ntTX', 'get_ServiceLocator_Xd9ntTXService', true],
            'App\\Controller\\CourseController::edit' => ['privates', '.service_locator.Xd9ntTX', 'get_ServiceLocator_Xd9ntTXService', true],
            'App\\Controller\\CourseController::index' => ['privates', '.service_locator.QkVYtxV', 'get_ServiceLocator_QkVYtxVService', true],
            'App\\Controller\\CourseController::new' => ['privates', '.service_locator.QkVYtxV', 'get_ServiceLocator_QkVYtxVService', true],
            'App\\Controller\\CourseController::newLesson' => ['privates', '.service_locator.5RpEjbl', 'get_ServiceLocator_5RpEjblService', true],
            'App\\Controller\\CourseController::show' => ['privates', '.service_locator.jqHm011', 'get_ServiceLocator_JqHm011Service', true],
            'App\\Controller\\LessonController::delete' => ['privates', '.service_locator.UqTc44d', 'get_ServiceLocator_UqTc44dService', true],
            'App\\Controller\\LessonController::edit' => ['privates', '.service_locator.UqTc44d', 'get_ServiceLocator_UqTc44dService', true],
            'App\\Controller\\LessonController::show' => ['privates', '.service_locator.pxaUkp_', 'get_ServiceLocator_PxaUkpService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CourseController:delete' => ['privates', '.service_locator.Xd9ntTX', 'get_ServiceLocator_Xd9ntTXService', true],
            'App\\Controller\\CourseController:edit' => ['privates', '.service_locator.Xd9ntTX', 'get_ServiceLocator_Xd9ntTXService', true],
            'App\\Controller\\CourseController:index' => ['privates', '.service_locator.QkVYtxV', 'get_ServiceLocator_QkVYtxVService', true],
            'App\\Controller\\CourseController:new' => ['privates', '.service_locator.QkVYtxV', 'get_ServiceLocator_QkVYtxVService', true],
            'App\\Controller\\CourseController:newLesson' => ['privates', '.service_locator.5RpEjbl', 'get_ServiceLocator_5RpEjblService', true],
            'App\\Controller\\CourseController:show' => ['privates', '.service_locator.jqHm011', 'get_ServiceLocator_JqHm011Service', true],
            'App\\Controller\\LessonController:delete' => ['privates', '.service_locator.UqTc44d', 'get_ServiceLocator_UqTc44dService', true],
            'App\\Controller\\LessonController:edit' => ['privates', '.service_locator.UqTc44d', 'get_ServiceLocator_UqTc44dService', true],
            'App\\Controller\\LessonController:show' => ['privates', '.service_locator.pxaUkp_', 'get_ServiceLocator_PxaUkpService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CourseController::delete' => '?',
            'App\\Controller\\CourseController::edit' => '?',
            'App\\Controller\\CourseController::index' => '?',
            'App\\Controller\\CourseController::new' => '?',
            'App\\Controller\\CourseController::newLesson' => '?',
            'App\\Controller\\CourseController::show' => '?',
            'App\\Controller\\LessonController::delete' => '?',
            'App\\Controller\\LessonController::edit' => '?',
            'App\\Controller\\LessonController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CourseController:delete' => '?',
            'App\\Controller\\CourseController:edit' => '?',
            'App\\Controller\\CourseController:index' => '?',
            'App\\Controller\\CourseController:new' => '?',
            'App\\Controller\\CourseController:newLesson' => '?',
            'App\\Controller\\CourseController:show' => '?',
            'App\\Controller\\LessonController:delete' => '?',
            'App\\Controller\\LessonController:edit' => '?',
            'App\\Controller\\LessonController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
