<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CourseRepository' shared autowired service.
     *
     * @return \App\Repository\CourseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CourseRepository'] = new \App\Repository\CourseRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
