<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLesson2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.pxaUkp_.App\Entity\Lesson' shared service.
     *
     * @return \App\Entity\Lesson
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pxaUkp_": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".');
    }
}
