<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLessonTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LessonType' shared autowired service.
     *
     * @return \App\Form\LessonType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LessonType'] = new \App\Form\LessonType(new \App\Form\DataTransformer\CourseToStringTransformer(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))));
    }
}
