<?php

namespace ContainerZ4vRQHr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLessonRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LessonRepository' shared autowired service.
     *
     * @return \App\Repository\LessonRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LessonRepository'] = new \App\Repository\LessonRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
