<?php

namespace ContainerQozgio3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqTc44dService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.UqTc44d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UqTc44d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lesson' => ['privates', '.errored..service_locator.UqTc44d.App\\Entity\\Lesson', NULL, 'Cannot autowire service ".service_locator.UqTc44d": it needs an instance of "App\\Entity\\Lesson" but this type has been excluded in "config/services.yaml".'],
            'lessonRepository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'lesson' => 'App\\Entity\\Lesson',
            'lessonRepository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
