<?php

namespace ContainerQozgio3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseToStringTransformerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\DataTransformer\CourseToStringTransformer' shared autowired service.
     *
     * @return \App\Form\DataTransformer\CourseToStringTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DataTransformer/CourseToStringTransformer.php';

        return $container->privates['App\\Form\\DataTransformer\\CourseToStringTransformer'] = new \App\Form\DataTransformer\CourseToStringTransformer(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
