<?php

namespace ContainerQozgio3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\CourseType' shared autowired service.
     *
     * @return \App\Form\CourseType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CourseType.php';

        return $container->privates['App\\Form\\CourseType'] = new \App\Form\CourseType();
    }
}
