<?php

namespace ContainerQozgio3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLessonTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\LessonType' shared autowired service.
     *
     * @return \App\Form\LessonType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LessonType.php';

        return $container->privates['App\\Form\\LessonType'] = new \App\Form\LessonType(($container->privates['App\\Form\\DataTransformer\\CourseToStringTransformer'] ?? $container->load('getCourseToStringTransformerService')));
    }
}
