<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4vRQHr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4vRQHr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZ4vRQHr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZ4vRQHr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZ4vRQHr\App_KernelProdContainer([
    'container.build_hash' => 'Z4vRQHr',
    'container.build_id' => '954e4f8b',
    'container.build_time' => 1710341921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4vRQHr');
