<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_course_index' => [[], ['_controller' => 'App\\Controller\\CourseController::index'], [], [['text', '/courses/']], [], [], []],
    'app_course_new' => [[], ['_controller' => 'App\\Controller\\CourseController::new'], [], [['text', '/courses/new']], [], [], []],
    'app_course_show' => [['id'], ['_controller' => 'App\\Controller\\CourseController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/courses']], [], [], []],
    'app_course_edit' => [['id'], ['_controller' => 'App\\Controller\\CourseController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/courses']], [], [], []],
    'app_course_delete' => [['id'], ['_controller' => 'App\\Controller\\CourseController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/courses']], [], [], []],
    'app_lesson_new' => [['id'], ['_controller' => 'App\\Controller\\CourseController::newLesson'], [], [['text', '/new/lesson'], ['variable', '', '[^/]++', 'id', true], ['text', '/courses']], [], [], []],
    'app_lesson_show' => [['id'], ['_controller' => 'App\\Controller\\LessonController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/lessons']], [], [], []],
    'app_lesson_edit' => [['id'], ['_controller' => 'App\\Controller\\LessonController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/lessons']], [], [], []],
    'app_lesson_delete' => [['id'], ['_controller' => 'App\\Controller\\LessonController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/lessons']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\CourseController::index'], [], [['text', '/']], [], [], []],
];
