<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQozgio3\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQozgio3/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQozgio3.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQozgio3\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerQozgio3\App_KernelTestDebugContainer([
    'container.build_hash' => 'Qozgio3',
    'container.build_id' => '62d3ac28',
    'container.build_time' => 1704304208,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQozgio3');
