<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrKNxpb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrKNxpb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJrKNxpb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJrKNxpb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJrKNxpb\App_KernelDevDebugContainer([
    'container.build_hash' => 'JrKNxpb',
    'container.build_id' => '6cd86ae8',
    'container.build_time' => 1704279173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrKNxpb');
